# Secrets never appear in task definitions, images or CI logs: ECS injects them
# from Secrets Manager at container start.

resource "random_password" "jwt" {
  length  = 64
  special = false
}

resource "random_id" "encryption_key" {
  byte_length = 32
}

# Generated by Terraform.
resource "aws_secretsmanager_secret" "app" {
  name                    = "${local.name}/app"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id
  secret_string = jsonencode({
    DATABASE_URL   = "postgresql://${var.db_username}:${random_password.db.result}@${aws_db_instance.main.address}:5432/hrms?sslmode=require&connection_limit=10"
    JWT_SECRET     = random_password.jwt.result
    ENCRYPTION_KEY = random_id.encryption_key.b64_std
    RABBITMQ_URL    = replace(aws_mq_broker.main.instances[0].endpoints[0], "amqps://", "amqps://hrms:${random_password.rabbitmq.result}@")
    REDIS_URL      = "rediss://:${random_password.redis.result}@${aws_elasticache_replication_group.main.primary_endpoint_address}:6379"
  })
}

# Third-party credentials, filled in by an operator in the AWS console/CLI.
# Terraform only creates the shape; it never overwrites values you set.
resource "aws_secretsmanager_secret" "integrations" {
  name                    = "${local.name}/integrations"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "integrations" {
  secret_id = aws_secretsmanager_secret.integrations.id
  secret_string = jsonencode({
    STRIPE_SECRET_KEY       = ""
    STRIPE_WEBHOOK_SECRET   = ""
    STRIPE_PRICE_BASIC      = ""
    STRIPE_PRICE_BUSINESS   = ""
    STRIPE_PRICE_ENTERPRISE = ""
    GEMINI_API_KEY          = ""
    GOOGLE_CLIENT_ID        = ""
    GOOGLE_CLIENT_SECRET    = ""
    SENTRY_DSN              = ""
  })
  lifecycle {
    ignore_changes = [secret_string]
  }
}
